let state={},selected='grok';
const names={grok:'Grok',claude:'Claude',codex:'Codex'},colors={grok:'#b4a6f5',claude:'#dca888',codex:'#8ac9b4'};
const $=id=>document.getElementById(id),known=value=>typeof value==='string'&&!['auto','unknown','unavailable',''].includes(value);
function timestamp(value){if(typeof value==='number')return value<1e11?value*1000:value;return Date.parse(value);}
function formatTime(value){const time=timestamp(value);return Number.isFinite(time)?new Date(time).toLocaleString('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}):'확인 불가';}
function render(){const p=state.snapshot?.providers?.find(p=>p.provider===selected);const q=p?.quota??{};const valid=typeof q.usedPercent==='number'&&Number.isFinite(q.usedPercent);const stale=!!state.error||q.stale||state.snapshot?.generatedAt&&Date.now()-Date.parse(state.snapshot.generatedAt)>150000;
  document.documentElement.dataset.provider=selected;
  document.documentElement.dataset.usage=stale?'stale':q.state==='exhausted'?'limited':!valid?'unknown':q.usedPercent>=90?'limited':q.usedPercent>=70?'warning':'ready';
  const missing=q.unavailableReason==='missing_percentage';
  document.documentElement.style.setProperty('--accent',colors[selected]);$('name').textContent=names[selected];$('avatar').textContent=names[selected][0];$('connection').textContent=!p?'상태를 가져오는 중':p.enabled===false?'사용 중지':p.available===false?'CLI 연결 확인 필요':p.authenticated===false?'로그인 필요':p.authenticated===true?'로그인됨 · 로컬 CLI':'로그인 상태 확인 불가';
  const windowLabel=q.windows?.find(w=>w.id===q.selectedWindow)?.label;
  $('quota-label').textContent=[windowLabel,stale?'마지막 확인값':q.limitKind==='rate_limited'?'요청 제한':q.state==='exhausted'?'사용 제한':valid?'사용됨':missing?'사용률 미제공':'확인 불가'].filter(Boolean).join(' · ');$('used').textContent=valid?`${q.usedPercent}%`:(missing?'미제공':'—');$('remaining').textContent=typeof q.remainingPercent==='number'?`${q.remainingPercent}% 남음`:missing?'자동 갱신 중':'잔여 사용률 확인 불가';$('fill').style.width=`${valid?Math.max(0,Math.min(100,q.usedPercent)):0}%`;$('fill').classList.toggle('warning',valid&&q.usedPercent>=70);
  $('quota-windows').replaceChildren();const windows=[...(q.windows??[])];
  if(selected==='claude'&&!windows.some(w=>w.id==='seven_day_fable'))windows.push({id:'seven_day_fable',label:'주간 · Fable',usedPercent:null,remainingPercent:null,resetsAt:null});
  const rank=id=>id==='five_hour'?0:id==='seven_day'?1:id==='seven_day_fable'?2:3;windows.sort((a,b)=>rank(a.id)-rank(b.id));$('quota-windows').hidden=windows.length===0;
  for(const window of windows){
    const row=document.createElement('div'),label=document.createElement('span'),values=document.createElement('b'),reset=document.createElement('small');
    const numeric=typeof window.usedPercent==='number'&&Number.isFinite(window.usedPercent),expired=Number.isFinite(timestamp(window.resetsAt))&&timestamp(window.resetsAt)<=Date.now();
    row.className='quota-window';row.dataset.window=window.id;label.textContent=selected==='claude'&&window.id==='seven_day'?'주간 · 전체 모델':window.label;
    values.dataset.usage=stale||expired||p?.authenticated!==true||!numeric?'unknown':window.usedPercent>=90?'limited':window.usedPercent>=70?'warning':'ready';
    values.textContent=numeric?`${window.usedPercent}% 사용${typeof window.remainingPercent==='number'?` · ${window.remainingPercent}% 남음`:''}`:'확인 불가';
    reset.textContent=`초기화 ${formatTime(window.resetsAt)}${expired?' · 마지막 확인값':''}`;row.append(label,values,reset);$('quota-windows').append(row);
  }
  const reset=timestamp(q.resetsAt);const mins=Number.isFinite(reset)?Math.ceil((reset-Date.now())/60000):0;const countdown=mins>0?mins>=60?`${Math.floor(mins/60)}시간 ${mins%60}분 후`:`${mins}분 후`:'';$('reset').textContent=`${formatTime(q.resetsAt)}${countdown?' · '+countdown:''}`;
  $('model').textContent=known(p?.model)?`${p.model} · 최근 관측`:known(p?.modelPolicy)?`설정 ${p.modelPolicy} · 실행값 미확인`:'자동 선택 · 실행 후 확인';$('model').title=`${p?.modelSource??''} · ${formatTime(p?.observedAt)}`;$('effort').textContent=known(p?.effort)?`${p.effort} · 최근 관측`:known(p?.effortPolicy)?`설정 ${p.effortPolicy} · 실행값 미확인`:'자동 · 실행 후 확인';$('effort').title=`${p?.effortSource??''} · ${formatTime(p?.observedAt)}`;$('auth').textContent=p?`${p.authenticated===true?'로그인됨':p.authenticated===false?'로그인 필요':'확인 불가'} / ${p.version??'확인 불가'}`:'확인 중';
  const accountStale=!!state.error||state.snapshot?.generatedAt&&Date.now()-Date.parse(state.snapshot.generatedAt)>150000||p?.account?.observedAt&&Date.now()-Date.parse(p.account.observedAt)>150000;
  const account=!accountStale&&p?.enabled!==false&&p?.available!==false&&p?.authenticated===true&&p.account?.status==='authenticated'?p.account:null;
  const identity=account?.email??account?.username??account?.displayName;
  $('account').textContent=identity??(!p?'확인 중':p.authenticated===false||p.account?.status==='unauthenticated'?'로그인 필요':p.authenticated===true&&account?'계정 정보 미제공':'확인 불가');
  $('account').title=account?`${account.source??'CLI'} · ${formatTime(account.observedAt)}`:'';
  $('organization-row').hidden=!account?.organization;$('organization').textContent=account?.organization??'';$('organization').title=account?.organization??'';
  const jobs=(state.snapshot?.jobs??[]).filter(job=>job.providers?.some(value=>value.provider===selected)).slice(0,2);$('job-count').textContent=jobs.length?`${jobs.length}개`:'';$('jobs').replaceChildren();if(!jobs.length){const empty=document.createElement('p');empty.className='empty';empty.textContent='기록된 최근 작업이 없습니다.';$('jobs').append(empty);}for(const job of jobs){const row=document.createElement('div'),name=document.createElement('span'),status=document.createElement('span');row.className='job';name.className='job-name';name.textContent=(job.project||'프로젝트')+(job.isolated?' · 격리 작업':'');name.title=job.isolated?`원래 프로젝트: ${job.originalCwd}\n실행 경로: ${job.cwd}`:(job.cwd||'');status.className='job-state';const value=job.providers.find(v=>v.provider===selected);const tokens=value?.usage?.totalTokens??value?.usage?.total_tokens;status.textContent=({running:'실행 중',queued:'대기',completed:'완료',failed:'실패',cancelled:'취소',cancelling:'취소 중',interrupted:'중단'})[job.status]??job.status;if(typeof tokens==='number')status.textContent+=` · ${tokens.toLocaleString()} tokens`;row.append(name,status);$('jobs').append(row);}
  $('refresh').disabled=state.refreshing;$('updated').textContent=state.refreshing?'새 상태를 확인하는 중…':selected==='claude'?`사용량 확인 ${formatTime(q.observedAt)} · 조회 캐시 5분`:`갱신 ${formatTime(state.snapshot?.generatedAt)} · 60초 간격`;$('fresh-dot').style.background=stale?'#d2ac7d':'#88cdb1';$('source').textContent=`출처: ${q.source??'unavailable'}`;$('notice').textContent=state.error||p?.reason||q.note||(q.limitKind==='rate_limited'?`재확인 ${formatTime(q.retryAfter)}`:!valid?'확인된 사용률만 표시합니다. 세션 토큰을 구독 잔여량으로 환산하지 않습니다.':'');
}
window.monitor.onState(value=>{state=value;render();});window.monitor.onProvider(value=>{if(value){selected=value;render();}});window.monitor.state().then(value=>{state=value;selected=value.selected??selected;render();});$('refresh').addEventListener('click',()=>window.monitor.refresh());document.addEventListener('keydown',event=>{if(event.key==='Escape')window.monitor.close();});setInterval(render,30000);
